--pl/sql is procedural language extension of sql
--syntax:
-- BEGIN
-- DBMS_OUTPUT.PUT_LINE("Hello World");
-- END
--store value:
-- declare
-- <declaration section>
-- begin
-- <executable exception>
--exception
-- <handle exception>
--end;
--/