--pl/sql is procedural language extension of sql
--syntax:
-- BEGIN
-- DBMS_OUTPUT.PUT_LINE("Hello World");
-- END
--store value:
-- declare
-- <declaration section>
-- begin
-- <executable exception>
--exception
-- <handle exception>
--end;
--/
--sample code:
-- declare
-- name varchar(12);
-- age int;
-- begin
-- name :='Rajesh';
-- age := 20;
-- dbms_output.put_line('my name is '||name);
-- dbms_output.put_line('my age is'||age);
-- end;
-- /

-- another example
-- declare
-- num number := 249;
-- begin
-- if mod(num,2)=0 then 
-- dbms_output.put_line('Even');
-- else 
-- dbms_output.put_line('odd');
-- end if;
-- end;
-- /
-- crud operation
-- begin
-- execute immediate 'create table emp(eid number,name varchar2(20))';
-- dbms_output.put_line('Table created succesfully');
-- end;
-- /